name: Project Pipeline 
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build_app:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: echo lint application
      - name: Transpile
        run: echo transpile code

  play_env_hmg:
    name: Deploy Application on HMG
    runs-on: ubuntu-latest
    needs: build_app
    environment:
      name: hmg
      url: https://hmg.google.com/
    steps:
      - name: Expose Secrets
        run: echo ${{ secrets.MY_SECRET }}
  
  run_robotframework_tests_action:
    name: Run tests against hmg
    runs-on: ubuntu-latest
    needs: play_env_hmg
    steps:
      - run: echo qq coisa
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          robot_tests_dir: tests
  
  play_env_prd:
    name: Deploy Application in PRD
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: https://google.com
    needs: run_robotframework_tests_action
    steps:
      - name: Expose Secrets
        run: echo ${{ secrets.MY_SECRET }}
            
          