name: Run Project
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Run_Robot_Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          robot_threads: 1
          robot_tests_dir: 'sample_project/test/tests/login/'
          robot_reports_dir: 'reports'
