name: Project Pipeline 
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init_job:
    runs-on: ubuntu-latest
    steps:
      - name: Any
        run: echo this is a job

  play_env_hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: https://google.com/q=${{ secrets.MY_SECRET }}
    needs: init_job
    name: Build and Deploy Application
    steps:
      - name: Expose Secrets
        run: echo ${{ secrets.MY_SECRET }}
  
  play_env_prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: https://google.com/q=${{ secrets.MY_SECRET }}
    needs: init_job
    name: Build and Deploy Application
    steps:
      - name: Expose Secrets
        run: echo ${{ secrets.MY_SECRET }}

  Run_robotframework_tests_action:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    needs: [play_env_hmg, play_env_prd]
    steps:
      - run: echo qq coisa
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          robot_tests_dir: tests
            
          