name: Run Project
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  play_env_hmg:
    runs-on: ubuntu-latest
    environment: hmg
    name: Build and Deploy Application
    steps:
      - name: Expose Secrets
        run: echo ${{ secrets.MY_SECRET }}
  
  play_env_prd:
    runs-on: ubuntu-latest
    environment: prd
    name: Build and Deploy Application
    steps:
      - name: Expose Secrets
        run: echo ${{ secrets.MY_SECRET }}

  Run_robotframework_tests_action:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    needs: [play_env_hmg, play_env_prd]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          robot_tests_dir: tests
            
          