name: Run Project
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Run_Robot_Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          browser: 'firefox'
          robot_threads: 2
          robot_tests_dir: 'sample_project/test/tests'
