name: Project Pipeline 
on: [push]
jobs:
  build_app:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: echo lint application
      - name: Transpile
        run: echo transpile code

  play_env_hmg:
    name: Deploy Application on HMG
    runs-on: ubuntu-latest
    needs: build_app
    environment:
      name: hmg
      url: https://hmg.google.com/
    steps:
      - name: Expose Secrets
        run: echo ${{ secrets.MY_SECRET }}
  
  run_robotframework_tests_action:
    name: Run tests against hmg
    runs-on: ubuntu-latest
    needs: play_env_hmg
    steps:
      - run: echo qq coisa
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run tests Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          robot_tests_dir: tests
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: reports
  
  generate_report:
        if: always()
        needs: [run_robotframework_tests_action] 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports
        - name: Send report to commit
          uses: joonvena/robotframework-reporter-action@v2.1
          with:
            gh_access_token: ${{ secrets.GB_TOKEN }}