name: Run Project
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Run_Robot_Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: echo ${{ github.workspace }}/sample_project/test/tests/login/
      - run: ls ${{ github.workspace }}/sample_project/test/tests/login/
      - run: ls sample_project/test/tests/login/
      - name: Robot Framework
        run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/sample_project/test/tests:/opt/robotframework/tests:Z \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
